### PR TITLE
0.13.2

### PR DESCRIPTION
**Pull request by nsheff**
Should we release a point before embarking full-throttle on 0.14? This already has all the project dashboard stuff which is pretty nice...

- [x] wait for https://github.com/pepkit/ubiquerg/pull/15
- [x] wait for https://github.com/pepkit/peppy/pull/324
- [x] wait for https://github.com/pepkit/looper/pull/212
- [x] version bump
- [x] changelog/docs update
- [x] Fix https://github.com/pepkit/caravel/issues/139

(probably worth going through the docs and making sure they're up-to-date)

### CODE REVIEW

**Comment by michalstolarczyk** [comment]
Yeah, it's worth a point release. Will need to revert the last two commits as they introduce the "add project" page, which is non-functional.

**Comment by nsheff** [comment]
good idea. just stick those ones on a separate branch, do the point release, and then we'll start on 0.14

**Comment by michalstolarczyk** [comment]
yup, that's what I did: https://github.com/pepkit/caravel/commits/add_project

I'm testing the `dev` now and will make the release today

**Comment by nsheff** [comment]
I just made the ubiquerg release in support of this.

**Comment by nsheff** [comment]
did you update requirements to the pending release versions of peppy and looper if they are required?

**Comment by michalstolarczyk** [comment]
yes, the requirements are updated

**Comment by michalstolarczyk** [comment]
this is good to from my perspective. after we release looper and peppy, of course

**Comment by nsheff** [comment]
you will need to update the peppy requirement.

I approved the peppy pr

**Comment by michalstolarczyk** [comment]
it is already set to 0.22.3, which is the peppy version to be released

**Pull request merged**
